import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

export const microsoftYahei = localFont({
  src: "./fonts/MicrosoftYaheifont.otf",
  variable: "--font-microsoft-yahei",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${microsoftYahei.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}
